name: JupyterGrADS CI

on: [push]

jobs:
  build:
    runs-on: [ubuntu-latest, macOS-latest, windows-latest]
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      shell: bash
      run: |
        pytest -W ignore::Warning
